AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  TuttiBot:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: ''
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: 'arn:aws:iam::210115261009:role/lambda-dynamo-lambda-role'
      Runtime: python3.7
      Timeout: 3
